### ISSUE TITLE
ngModel two-way bind

### ISSUE THREAD

**Issue by shenchaoran** [petkit-io/ngx-material-cascader#2]
Hello, I want use this component in form, so I make some change on it. Make it implements `ControlValueAccessor`, but I don't know why, the `ngModelChange` event couldn't be triggered, could you please help me about it? thanks!

reproduced [here](https://stackblitz.com/edit/mat-cascader?file=src%2Fapp%2Fmat-cascader%2Fmat-cascader.component.ts)

**Comment by soraliu** [comment]
@shenchaoran 
I have checked your code, you should not assign `fn` to same variable `propagateChange` in `registerOnTouched`. Remove or assign to another variable, it works.

**Comment by soraliu** [comment]
Hope you can write a pull request, our component need more contributors such as you. Thank you a lot. 😀
